Init nuxt & packages
kamilziemann/nuxt_crm pull request #1
Opened 2024-02-26 19:34 UTC by themari0pl

2024-02-26 20:06 UTC, lobarzanek requested changes

2024-02-26 20:06 UTC, lobarzanek commented on components/Footer/index.vue
Remove this component with the parent folder. We don't plan to use it in this project

2024-02-26 20:06 UTC, lobarzanek commented on app.vue
> +    <Footer/>
Remove Footer component. We don't plan to use it in this project

2024-02-26 20:06 UTC, lobarzanek commented on app.vue
> +    <TopNav/>
Change TopNav to SideBar component

2024-02-26 20:06 UTC, lobarzanek commented on components/Top/Nav.vue
Remove this component and create a SideBar file instead. You can also rename it but clear it, leaving the component empty
You can use below path:
`components/Side/Bar.vue`

2024-02-26 20:06 UTC, lobarzanek commented on package.json
Add `json-server` to dependencies and create `db.json` file in main folder
https://www.npmjs.com/package/json-server

After it add 
`"json": "json-server --watch db.json --port 8000"`
to scripts section

  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
     "json": "json-server --watch db.json --port 8000",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },

2024-02-26 20:06 UTC, lobarzanek commented on pages/about.vue
Remove this page, we don't plan to use it in this project

2024-02-28 16:45 UTC, themari0pl commented on pages/about.vue
done.

2024-03-01 21:51 UTC, lobarzanek commented on components/Side/Bar.vue
> +      <NuxtPage/>
delete
`<SideBar/>`
`<NuxtPage/>`

2024-03-01 21:51 UTC, lobarzanek commented on nuxt.config.ts
> +  css: ['~/assets/css/main.css'],
Delete this line:
`css: ['~/assets/css/main.css'],`

You have this property currently in line 13
`css: ["~/assets/main.scss"]`

2024-03-01 21:51 UTC, lobarzanek commented on pages/about.vue
Delete this page, We don't use it in this project

2024-03-02 20:34 UTC, lobarzanek approved these changes

2024-03-02 21:42 UTC, kamilziemann approved these changes

2024-03-02 21:42 UTC, merged